CREATE TABLE PRODUCT(
ID INT AUTO_INCREMENT,
PROD_ID VARCHAR(10),
PROD_NAME VARCHAR(255),
PRICE DOUBLE,
ITEM_ID VARCHAR(10)
);
CREATE TABLE BOOK(
ID INT AUTO_INCREMENT,
BOOK_ID VARCHAR(10),
GENRE VARCHAR(255),
AUTHOR VARCHAR(255),
PUBLICATION VARCHAR(255)
);

CREATE TABLE APPAREL(
ID INT AUTO_INCREMENT,
APPAREL_ID VARCHAR(10),
TYPE VARCHAR(255),
BRAND VARCHAR(255),
DESIGN VARCHAR(255)
);

CREATE TABLE CART(
ID INT AUTO_INCREMENT,
PROD_ID VARCHAR(10),
PROD_NAME VARCHAR(255),
PROD_TYPE VARCHAR(255),
ITEM_ID VARCHAR(10),
COUNT DOUBLE,
PRICE DOUBLE
);

INSERT INTO BOOK VALUES(1,'B101','SUSPENSE','Ishwar Chandra Gupta','Deys Publishing');
INSERT INTO BOOK VALUES(2,'B102','COMEDY','Peary Chand Mitra','Patra Bharati');
INSERT INTO BOOK VALUES(3,'B103','EDUCATION','Sunil Bhandhopadhya','Mitra & Ghosh Publishers Private Limited');
INSERT INTO BOOK VALUES(4,'B104','SUSPENSE','Peary Chand Mitra','Setu Prakashani');
INSERT INTO BOOK VALUES(5,'B105','SPIRITUAL','Lal Behari Dey','Parul Prakashani Private Limited');
INSERT INTO BOOK VALUES(6,'B106','EDUCATION','Dinabandhu Mitra','Ananda Publishers Pvt Ltd');

INSERT INTO APPAREL VALUES(1,'A101','Kids','Allen Solly','Pant');
INSERT INTO APPAREL VALUES(2,'A102','Woman','Van Heusen','Pant');
INSERT INTO APPAREL VALUES(3,'A103','Woman','Park Avenue','Shorts');
INSERT INTO APPAREL VALUES(4,'A104','Man','Park Avenue','Jeans');
INSERT INTO APPAREL VALUES(5,'A105','Kids','Allen Solly','Jackets');
INSERT INTO APPAREL VALUES(6,'A106','Woman','Van Heusen','Sweaters');
INSERT INTO APPAREL VALUES(7,'A107','Man','Pepe Jeans','Sweaters');
INSERT INTO APPAREL VALUES(8,'A108','Kids','Allen Solly','Jackets');
INSERT INTO APPAREL VALUES(9,'A109','Man','Wrangler','Shirts');

INSERT INTO PRODUCT VALUES(1,'P101','Shonku Samagra',120,'B101');
INSERT INTO PRODUCT VALUES(2,'P102','Gora',255,'B102');
INSERT INTO PRODUCT VALUES(3,'P103','Devdas',235,'B103');
INSERT INTO PRODUCT VALUES(4,'P104','Moon Mountain',220,'B104');
INSERT INTO PRODUCT VALUES(5,'P105','Chokher Bali',420,'B105');
INSERT INTO PRODUCT VALUES(6,'P106','Sanchaita',550,'B106');

INSERT INTO PRODUCT VALUES(7,'P107','Lovely Lady Clothing',2560,'A101');
INSERT INTO PRODUCT VALUES(8,'P108','Studio 51 Clothing Co.',1120,'A102');
INSERT INTO PRODUCT VALUES(9,'P109','Sweet Tea Dresses',1250,'A103');
INSERT INTO PRODUCT VALUES(10,'P110','Serafina Women Label',850,'A104');
INSERT INTO PRODUCT VALUES(11,'P111','Too Tempted Clubwear',950,'A105');
INSERT INTO PRODUCT VALUES(12,'P112','Hourglass Jeans',1200,'A106');
INSERT INTO PRODUCT VALUES(13,'P113','South City Streetwear',1100,'A107');
INSERT INTO PRODUCT VALUES(14,'P114','Hot Head Threads',950,'A108');
INSERT INTO PRODUCT VALUES(15,'P115','Threadhunter',1250,'A109');
